# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='Validated_time',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='通过验证次数'),
        ),
    ]
