# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0002_proxy_validated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='district',
            field=models.CharField(default='其他', max_length=50, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='type',
            field=models.CharField(choices=[('G', '高匿'), ('T', '透明'), ('O', '其他')], default='O', max_length=20, verbose_name='类型'),
        ),
    ]
