# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0003_auto_20170405_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='head',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Head'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='port',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Port'),
        ),
    ]
