# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0004_auto_20170422_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='addr',
        ),
        migrations.AddField(
            model_name='proxy',
            name='failed_time',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='连续验证失败次数'),
        ),
    ]
