# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0005_auto_20170422_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='failed_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='连续验证失败次数'),
        ),
    ]
