# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproxy', '0006_auto_20170423_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100, verbose_name='请求IP地址')),
                ('req_count', models.IntegerField(default=0, verbose_name='总请求次数')),
                ('limit_count', models.IntegerField(default=0, verbose_name='限制请求次数')),
                ('limit', models.CharField(choices=[('T', '限制'), ('F', '不限制')], default='F', max_length=10, verbose_name='限制访问')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
